version: '3'
services:
  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: database_name
      MYSQL_ROOT_PASSWORD: database_password
      MYSQL_INITDB_SKIP_TZINFO: 1
    volumes:
      - testbed-db:/var/lib/mysql
  php:
    build: .
    environment:
      BOGUS: 'yes'
      #AUTH_KEY: generateme
      #AUTH_SALT: generateme
      #DB_HOST: db
      #DB_NAME: database_name
      #DB_PASSWORD: database_password
      #DB_USER: root
      #LOGGED_IN_KEY: generateme
      #LOGGED_IN_SALT: generateme
      #NONCE_KEY: generateme
      #NONCE_SALT: generateme
      #SECURE_AUTH_KEY: generateme
      #SECURE_AUTH_SALT: generateme
      #WP_ENV: development
      #WP_HOME: http://bedrock.test
      #WP_SITEURL: http://bedrock.test/wp
    volumes:
      - ./site:/code
      - ./config/php.ini:/usr/local/etc/php/conf.d/bedrock.ini
    depends_on:
      - db
    links:
      - db
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./site:/code
      - ./config/site.nginx.conf:/etc/nginx/conf.d/site.nginx.conf
    links:
      - php

volumes:
  testbed-db:
